comment:
  on-update: recreate
  header: |
    Hey ${{ author }}, thank you for submitting this PR.

  footer: |
    ---
    Please ping @J08K and @BethanyG for help!

  snippets:
    - id: any-markdown-file-changed
      files:
        - '*.md'
        - '**/*.md'
      body: |
        It looks like you're changing a Markdown file.
        Make sure your changes follow our [language guidelines](some-link) when writing documentation.