name: PR Commenter
description: Action for automatically commenting on newly created PRs.
on:
  - pull_request_target

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: ${{ github.token }}
          config-file: ".github/hacktoberfest-prs.yml"
          template-variables: |
            {
              "author": "${{ github.event.pull_request.user.login }}"
            }