name: "PR Commenter"
on:
  - pull_request_target

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate some template variables
        id: vars
        run: |
          echo ::set-output name=today::"$(date +%d-%m-%Y)"

      - uses: exercism/pr-commenter-action@v1.3.0
        with:
          template-variables: |
            {
              "today": "${{ steps.vars.outputs.today }}",
              "prAuthor": "${{ github.event.pull_request.user.login }}",
              "branchNamePrefix": ${{ startsWith(github.event.pull_request.head.ref, 'ref-') }}
            }